---
filebeat_version: 7.x
filebeat_package: filebeat
filebeat_package_state: present

filebeat_create_config: true
filebeat_template: "filebeat.yml.j2"

filebeat_inputs:
  - type: log
    paths:
      - "/var/log/*.log"

filebeat_output_elasticsearch_enabled: false
filebeat_output_elasticsearch_hosts:
  - "es-node-1.plumotech.com:9300"

filebeat_output_logstash_enabled: true
filebeat_output_logstash_hosts:
  - "10.253.54.85:5042"
  - "10.253.54.85:5043"
  - "10.253.54.85:5044"
filebeat_output_fluentd_hosts:
  - "fluentd.plumotech.com:5042"
  - "fluentd.plumotech.com:5043"
  - "fluentd.plumotech.com:5044"
filebeat_enable_logging: false
filebeat_log_level: warning
filebeat_log_dir: /var/log/mybeat
filebeat_log_filename: mybeat.log

filebeat_ssl_certificate_logstash: "yes"
filebeat_ssl_certificate_elasticsearch: "no"
filebeat_ssl_dir: /etc/pki/logstash
filebeat_ssl_certificate_file: ""
filebeat_ssl_key_file: ""
filebeat_ssl_insecure: "false"

filebeat_elastic_cloud_enabled: false
filebeat_elastic_cloud_id: ""
filebeat_elastic_cloud_username: ""
filebeat_elastic_cloud_password: ""
