---
- block: ############filebeat############
  - name: include vars
    include_vars: file='filebeat.yml' 
  - name: Ensure required dependencies are present.
    apt:
      name:
        - apt-transport-https
        - gnupg2
      state: present

  - name: Add Elasticsearch apt key.
    apt_key:
      url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
      id: 46095ACC8548582C1A2699A9D27D666CD88E42B4
      state: present

  - name: Add Filebeat repository.
    apt_repository:
      repo: 'deb https://artifacts.elastic.co/packages/{{ filebeat_version }}/apt stable main'
      state: present
      update_cache: true

  - name: Install Filebeat.
    package:
      name: "{{ filebeat_package }}"
      state: "{{ filebeat_package_state }}"

  - name: Copy Filebeat configuration.
    template:
      src: "{{ filebeat_template }}"
      dest: "/etc/filebeat/filebeat.yml"
      owner: root
      group: root
      mode: 0644
    notify: restart filebeat

  - name: Ensure Filebeat is started and enabled at boot.
    service:
      name: filebeat
      state: started
      enabled: true
  tags: filebeat
