---
# tasks file for osupgrade
- name: Update apt repo and cache
  ansible.builtin.apt:
    update_cache: true
    name: psmisc
    state: present

- name: Wait for APT Lock
  ansible.builtin.shell: |
    while sudo fuser /var/lib/{{ item }} >/dev/null 2>&1; do sleep 5; done;
  loop:
    - dpkg/lock
    - dpkg/lock-frontend
    - apt/lists/lock
  retries: 5
  delay: 3

- name: Upgrade all packages on servers
  ansible.builtin.apt:
    upgrade: full
    force_apt_get: true
  async: 3600
  poll: 0

- name: Check if a reboot is needed on all servers
  ansible.builtin.stat:
    path: /var/run/reboot-required
    get_checksum: false
  register: reboot_required_file
  retries: 5

- name: Reboot the server if kernel updated
  ansible.builtin.reboot:
    msg: "Reboot initiated by Ansible for kernel updates"
    connect_timeout: 5
    reboot_timeout: 900
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
  when: reboot_required_file.stat.exists

- name: Wait for APT Lock
  ansible.builtin.shell: |
    while sudo fuser /var/lib/{{ item }} >/dev/null 2>&1; do sleep 5; done;
  loop:
    - dpkg/lock
    - dpkg/lock-frontend
    - apt/lists/lock
  retries: 5
  delay: 3

- name: Remove dependencies that are no longer required
  ansible.builtin.apt:
    autoremove: true
